from .VerifiedSeisms import VerifiedSeisms as VerifiedSeismsResource
from .VerifiedSeisms import VerifiedSeisms1 as VerifiedSeisms1Resource
from .UnverifiedSeisms import UnverifiedSeisms as UnverifiedSeismsResource
from .UnverifiedSeisms import UnverifiedSeisms1 as UnverifiedSeisms1Resource